combine_control_expr       = false
comment_width              = 255
edition                    = "2018"
format_macro_matchers      = true
imports_granularity        = "Crate"
imports_layout             = "Vertical"
match_block_trailing_comma = true
max_width                  = 160
newline_style              = "Native"
overflow_delimited_expr    = true
reorder_impl_items         = true
reorder_imports            = true
struct_lit_single_line     = false
tab_spaces                 = 2
use_field_init_shorthand   = true
use_try_shorthand          = true
version                    = "Two"
where_single_line          = true
